services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    env_file:
      - .env

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
